# Generated by Django 4.2.1 on 2023-05-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_desk', '0002_remove_guest_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housekeepingtask',
            name='room',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='MaintenanceRequest',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HousekeepingTask',
        ),
        migrations.DeleteModel(
            name='MaintenanceRequest',
        ),
    ]
