# Generated by Django 4.2.1 on 2023-05-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_desk', '0003_remove_housekeepingtask_room_delete_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='checking',
            field=models.CharField(choices=[('Checked In', 'Checked In'), ('Checked Out', 'Checked Out'), ('No Show', 'No Show'), ('Maintenance', 'Maintenance')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='availability',
            field=models.CharField(choices=[('Clean', 'Clean'), ('Dirty', 'Dirty')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.CharField(choices=[('Clean', 'Clean'), ('Dirty', 'Dirty'), ('Turn Down', 'Turn Down')], max_length=50),
        ),
    ]
