# Generated by Django 4.2.1 on 2023-05-19 20:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('front_desk', '0004_reservation_checking_room_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='days_left',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='event_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reservation',
            name='event_type',
            field=models.CharField(choices=[('Reserve', 'Reserve'), ('Arriving', 'Arriving'), ('Staying Over', 'Staying Over'), ('Departing', 'Departing')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='total_charge',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='checking',
            field=models.CharField(choices=[('Checked In', 'Checked In'), ('Checked Out', 'Checked Out'), ('No Show', 'No Show')], max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='availability',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Maintenance', 'Maintenance'), ('Complimentary', 'Complimentary')], max_length=50),
        ),
    ]
