# Generated by Django 4.2.1 on 2023-05-23 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_desk', '0005_reservation_days_left_reservation_event_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='special_requests',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
