# Generated by Django 4.2.1 on 2023-05-24 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('front_desk_manager', 'Front Desk Manager'), ('auditor', 'Auditor'), ('manager', 'Manager'), ('general_manager', 'General Manager'), ('supervisor', 'Supervisor'), ('owner', 'Owner'), ('bar_staff', 'Bar_staff')], max_length=20),
        ),
    ]
